name: Verificador de Sismos Fortes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar JQ
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Verificar API e Enviar Notificação de Teste
        run: |
          # --- Informações de TESTE ---
          # Esta API busca o sismo mais recente de qualquer magnitude
          API_URL="https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minmagnitude=1.0&limit=1&orderby=time"
          FCM_KEY="${{ secrets.FCM_SERVER_KEY }}"

          # Baixa o JSON da API
          FEED_CONTENT=$(curl -s "$API_URL")

          # Extrai o título e a magnitude do sismo mais recente de forma segura
          CURRENT_TITLE=$(echo "$FEED_CONTENT" | jq -r '.features[0].properties.title')
          CURRENT_MAGNITUDE=$(echo "$FEED_CONTENT" | jq -r '.features[0].properties.mag')

          echo "Sismo de teste encontrado: $CURRENT_TITLE (M$CURRENT_MAGNITUDE)"

          # Monta o corpo da notificação de TESTE
          JSON_BODY=$(jq -n \
            --arg to "/topics/ALERTAS_SISMOS_FORTES" \
            --arg title "TESTE: Sismo de Magnitude $CURRENT_MAGNITUDE" \
            --arg body "O sismo mais recente detectado foi: $CURRENT_TITLE" \
            --arg sound "default" \
            '{
              "to": $to,
              "notification": {
                "title": $title,
                "body": $body,
                "sound": $sound
              }
            }' \
          )

          # Envia a notificação para o Firebase
          curl -X POST -H "Authorization: key=$FCM_KEY" -H "Content-Type: application/json" \
            -d "$JSON_BODY" https://fcm.googleapis.com/fcm/send

          echo "Notificação de teste enviada para o Firebase."

          # Este script de teste não salva IDs, então não é necessário o git push
