name: Verificador de Sismos Fortes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl python3 python3-pip
          pip3 install google-auth

      - name: Gerar token OAuth 2.0 com chave JSON
        id: auth
        run: |
          printf '%s' "${{ secrets.FCM_SERVICE_ACCOUNT_JSON }}" > service-account.json

          ACCESS_TOKEN=$(python3 - <<EOF
          import json
          import google.auth
          from google.auth.transport.requests import Request
          from google.oauth2 import service_account

          creds = service_account.Credentials.from_service_account_file(
              'service-account.json',
              scopes=['https://www.googleapis.com/auth/firebase.messaging']
          )
          creds.refresh(Request())
          print(creds.token)
          EOF
          )

          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Verificar API e Enviar Notificação de Teste
        run: |
          API_URL="https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minmagnitude=1.0&limit=1&orderby=time"

          FEED_CONTENT=$(curl -s "$API_URL")
          CURRENT_TITLE=$(echo "$FEED_CONTENT" | jq -r '.features[0].properties.title')
          CURRENT_MAGNITUDE=$(echo "$FEED_CONTENT" | jq -r '.features[0].properties.mag')

          echo "Sismo de teste encontrado: $CURRENT_TITLE (M$CURRENT_MAGNITUDE)"

          JSON_BODY=$(jq -n \
            --arg title "TESTE: Sismo de Magnitude $CURRENT_MAGNITUDE" \
            --arg body "O sismo mais recente detectado foi: $CURRENT_TITLE" \
            '{
              "message": {
                "topic": "ALERTAS_SISMOS_FORTES",
                "notification": {
                  "title": $title,
                  "body": $body
                }
              }
            }'
          )

          curl -X POST \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$JSON_BODY" \
            https://fcm.googleapis.com/v1/projects/streamnewapp/messages:send

          echo "Notificação enviada com sucesso via API HTTP v1."
