name: Verificador de Sismos Fortes

on:
  schedule:
    # Roda a cada 1 minuto para testes
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar JQ
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Verificar API e Enviar Notificação
        run: |
          # Define as variáveis importantes para TESTE
          # Busca sismos a partir de M2.5 com filtro de 1 minuto
          API_URL="https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minmagnitude=2.5&starttime=$(date -u -d '1 minutes ago' +'%Y-%m-%dT%H:%M:%S')&orderby=time"
          FCM_KEY="${{ secrets.FCM_SERVER_KEY }}"
          
          # Pega o ID do último sismo que notificamos
          LAST_ID_FILE="last_quake_id.txt"
          if [ -f "$LAST_ID_FILE" ]; then
            LAST_ID=$(cat "$LAST_ID_FILE")
          else
            LAST_ID="initial"
          fi

          FEED_CONTENT=$(curl -s "$API_URL")
          QUAKES=$(echo "$FEED_CONTENT" | jq -c '.features[]')
          
          # Extrai o ID do sismo mais recente para atualizar o arquivo de controle
          FIRST_QUAKE_ID=$(echo "$QUAKES" | head -n 1 | jq -r '.id')

          # Itera sobre cada sismo do feed
          echo "$QUAKES" | while read -r QUAKE; do
            CURRENT_ID=$(echo "$QUAKE" | jq -r '.id')
            CURRENT_TITLE=$(echo "$QUAKE" | jq -r '.properties.title')

            echo "Último ID processado: $LAST_ID"
            echo "ID do sismo atual: $CURRENT_ID"

            if [ "$CURRENT_ID" != "$LAST_ID" ]; then
              echo "Novo sismo detectado! Título: $CURRENT_TITLE"
              
              JSON_BODY=$(jq -n \
                          --arg id "$CURRENT_ID" \
                          --arg title "$CURRENT_TITLE" \
                          --arg to "/topics/ALERTAS_SISMOS_FORTES" \
                          '{to: $to, notification: {title: "Significant Earthquake: \($title)", body: "A significant earthquake has been detected. Tap to open StreamNew Monitor for details.", sound: "default"}}')

              curl -X POST -H "Authorization: key=$FCM_KEY" -H "Content-Type: application/json" \
                   -d "$JSON_BODY" https://fcm.googleapis.com/fcm/send

            else
              echo "Nenhum sismo novo detectado."
              break
            fi
          done

          # Adiciona uma nova lógica para salvar o ID do sismo mais recente de forma segura
          if [ -n "$FIRST_QUAKE_ID" ]; then
             echo "$FIRST_QUAKE_ID" > "$LAST_ID_FILE"
             git config --global user.name 'GitHub Actions'
             git config --global user.email 'actions@github.com'
             git add $LAST_ID_FILE
             git commit -m "Atualiza o ID do último sismo processado"
             git push
          fi
